### ISSUE TITLE
Doesn't work: Loops back to asking for permission

### ISSUE THREAD

**Issue by carlos1172** [davidlang42/taskban#1]
Hello,

I tried using this but it doesn't work anymore. It just loops back to asking for permission again.
1. I go to https://taskban.davidlang.net
2. It redirects to https://script.google.com/macros/s/AKfycbxSDJouDbOKVTQ3cnnGaJaLW5EbR86YRTwCX-PJb7Mvua9egDM/exec?redirect=
3. It says Review Permissions 
![image](https://user-images.githubusercontent.com/51019601/131241266-6ce33d78-488e-45e6-8fe2-1ecd5e0b0c01.png)
4. I press allow 
![image](https://user-images.githubusercontent.com/51019601/131241272-8312c1f4-bbcb-44a4-b952-ba856e412097.png)
5. It loops back to #3

**Comment by davidlang42** [comment]
That's very strange. Unfortunately the OAuth is all handled by Google so its very hard for me to know what is going wrong, or what I may have changed which affected their OAuth from succeeding. I'll do some digging when I get a chance but I probably won't have time until next week.

Thanks for letting me know!

**Comment by carlos1172** [comment]
I see. Well I hope we find a work around. Thanks for getting back to me, and no rush on the fix. :)

Regards,
Carlos Resurreccion

**Comment by davidlang42** [comment]
Thanks @GuizmoPhil for figuring that out! There's also been some issues with how I do the redirect, as noted in [another issue](https://github.com/davidlang42/taskban/issues/3), see that issue for more details.
