### ISSUE TITLE
Popup in Firefox browser

### ISSUE THREAD

**Issue by Eburon8** [davidlang42/taskban#21]
The app won't launch on the Firefox browser via the shortcut in workspace.
It opens a popup window (once you allow popups from google.com), but presents an error.

The error:
  403. That’s an error.

  We're sorry, but you do not have access to this page. That’s all we know.

It does work in a browser window if you whitelist https://taskban.davidlang.net for tracking cookies.

**Comment by davidlang42** [comment]
Hi @Eburon8 , unfortunately all cookies generated/required by the web app are from Google. Google controls the authentication and there's no way I can modify, or even read, the cookies it writes with any of my code.

So you'll have to whitelist whatever cookies Google has decided are necessary for its authentication system, or you won't be able to use this Google-hosted app.
