### ISSUE TITLE
Not Seeing Assigned Tasks

### ISSUE THREAD

**Issue by asp-ball** [davidlang42/taskban#22]
Great Addon - love it! But it is not seeing tasks assigned to me from a Google Doc or Sheet. I see them in the task list (only one list To Do) but not in taskban.

**Comment by davidlang42** [comment]
Unfortunately Google handles the tasks from Sheets and Docs in an entirely separate system, and doesn't actually store them in Google Tasks, therefore they aren't accessible in TaskBan (and there's no way they could be).
