### ISSUE TITLE
It would show duplicate items when adding new task to the taskban

### ISSUE THREAD

**Issue by reply2future** [davidlang42/taskban#5]
## problem
![Snipaste_2021-12-30_09-30-52](https://user-images.githubusercontent.com/6359152/147714668-aef6126f-4256-4d31-811c-b71a03bf24ee.png)
## reproduce
1. add task to the todo using the taskban

**Comment by davidlang42** [comment]
Hi @reply2future, can you give me more information about when this occurs or how you are accessing TaskBan? Unfortunately on my end, it does not duplicate a new task which is added.

Also, if you refresh (either by refreshing the browser or clicking the refresh icon in the top right) does the duplicate go away?

**Comment by reply2future** [comment]
Sure,here is more informations
```text
macos: Monterey 12.1
chrome: Version 96.0.4664.110 (Official Build) (arm64)
network：Internet censored area
usage: 
  click the right area of google calendar and then click the task list, 
  it would show me the window and the url is `https://taskban.davidlang.net/frame.html?b=Workflow`
```

> Also, if you refresh (either by refreshing the browser or clicking the refresh icon in the top right) does the duplicate go away?

Yes, both works.

When I reopen the window and tried again,the problem was gone. 😕  My laptop is always sleeping instead of shuting down, and I guess the network would be the problem also. I would try to collect more infos later.

Btw, thanks for your great tools.

**Comment by reply2future** [comment]
It didn't happend again when I used it every day through half months,so closed the issue.
